### ISSUE TITLE
Additional Language Support

### ISSUE THREAD

**Issue by cammoore1** [cammoore1/DAI-proton-ge-custom#2]
This is an issue thread for adding support for other languages' versions to DAI-Proton. Currently added languages are English as of v1.0.4. If your language's version is not listed, please follow the directions and we may be able to add support for it.

1. Go to where you placed the files for DAI-Proton-1.0.4 and open it.
2. Open "user_settings.sample.py" in a text editor.
3. Change the line that says #"WINEDEBUG": "+timestamp,+pid,..." to "WINEDEBUG": "fixme-all,+win" . Make sure that the line is copied exactly. No space should be between the comma and +win or it will not log the information needed correctly.
4. Make sure you uncomment the line by removing the # symbol at the start of it.
5. Change the name of the "user_settings.sample.py" file to "user_settings.py"
6. Start the game using DAI-Proton-1.0.4. Ensure "Force the use of a specific Steam Play compatibility tool" is turned on with the correct proton version set.
7. After getting to the marching soldiers screen, close the game.
8. A log file will have been generated in your Home directory named steam-1222690.log. You should upload it here in a comment.
9. Change the name of the "user_settings.py" file to "user_settings.sample.py". If you don't, then it will continue generating log files that will take up a lot of space if you continue to use this proton version.

**Comment by TheoMzr** [comment]
[steam-1222690.log](https://github.com/user-attachments/files/15521697/steam-1222690.log)

**Comment by TheoMzr** [comment]
[steam-1222690.log](https://github.com/user-attachments/files/15523400/steam-1222690.log)

**Comment by Alpharick** [comment]
[steam-1222690.log](https://github.com/user-attachments/files/15793696/steam-1222690.log)

**Comment by italoghost** [comment]
Hi! Here it is the log for Brazilian Portuguese version, using Proton + Heroic. It didn't work, unfortunately. 

I tried adding to Steam to see if the Steam API would help but it didn't.

It is strange, as the processes have the same name ("GameLoop" and "DragonAgeInquis").

[steam-heroic-0.log](https://github.com/user-attachments/files/15894363/steam-heroic-0.log)

**Comment by italoghost** [comment]
Update on my latest comment: moved to Lutris + Proton DAI + Umu-Launcher and it worked! I didn't even need the Steam Input API!
