### ISSUE TITLE
No longer launches game on Steam Deck

### ISSUE THREAD

**Issue by Tallera257** [cammoore1/DAI-proton-ge-custom#5]
I have the 1TB OLED Steam Deck.  I discovered this workaround for the controls about a week ago, and have been playing on my Steam Deck up to last night (around 11:30pm EDT).  I went to pick it up today around 12:00pm EDT, and when I launch the game, it launches the EA app, but no longer launches the actual game afterwards.  It shows the EA app "library" screen, and when I try to manually select DAI and launch the game, it either (a) tells me the game is already running (happened once, haven't been able to recreate so far), or (b) doesn't seem to do anything (happened twice).

When I launch the game on my PC (which, of course, works as usual), my most recent save is several hours behind the last saved game I created from last night on my Steam Deck.  That last part isn't your problem, obviously, but it's frustrating because if I don't want to redo 1-2 hours of playtime, I need to figure out how to get the game running on my Deck again. ;P

I tried to see if the EA app updated overnight, but I haven't found a way to tell yet.  Thanks for any help you can offer! :)

**Comment by PinkTuxedo** [comment]
@Tallera257 I believe the latest OS update on the Steam Deck broke this. Switch your Deck from Stable to Beta for a workaround.

**Comment by Tallera257** [comment]
AHAHAHAHHHH!!!  Yes, that did work!  It got a bit more complicated when my cloud save and local save conflicted (had to run in desktop mode first so I could choose the option of which save to continue with).  But now it seems to be working fine.

Thanks for the tip! 😀

**Comment by hendkai** [comment]
> @Tallera257 I believe the latest OS update on the Steam Deck broke this. Switch your Deck from Stable to Beta for a workaround.

Which Proton Version Do you use? For me Dai ori Experimental wont work with beta.
